# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

run:
  concurrency: 4
  deadline: 10m

  # skip-dirs: []

  # skip-files: []
  modules-download-mode: readonly

linters:
  disable:
  - unused

issues:
  exclude-rules:
  - linters:
    - staticcheck
    text: "SA1019:" # Excludes messages where deprecated variables are used
